version: "3"
services:
  zentrale:
    image: zentrale:latest
    ports:
    - 5000:5000/udp
    - 9000:9000/tcp
    restart: "no"

  verbraucher1:
    image: verbraucher:latest
    restart: "no"

  verbraucher2:
    image: verbraucher:latest
    restart: "no"

  erzeuger1:
    image: erzeuger:latest
    restart: "no"